// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('iniciar sesion bien', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('iniciar sesion bien', async function() {
    await driver.get("http://localhost:5173/")
    await driver.manage().window().setRect({ width: 1168, height: 818 })
    await driver.findElement(By.css(".btn-login")).click()
    await driver.findElement(By.css(".flex-col > .w-full:nth-child(1)")).sendKeys("alu0101540153@ull.edu.es")
    await driver.findElement(By.css(".w-full:nth-child(2)")).sendKeys("12345678")
    await driver.findElement(By.css("button")).click()
  })
})
